---
asciidoc:
  attributes:
      page-pagination: ''
  extensions:
    - "asciidoctor-kroki"
    - "@djencks/asciidoctor-mathjax"

site:
  title: Ivan Ponomarev, PhD
  start_page: ROOT::index.adoc
  robots: allow

urls:
  html_extension_style: default
  latest_version_segment: latest
content:
  sources:
  - url: ./
    branches: HEAD
    worktrees: false

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
...
