---
name: Build Docs

on:
  push:
  workflow_dispatch:

jobs:
  deploy-docs:
    name: deploy-docs
    environment: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm i
      - run: npx antora --fetch antora-playbook.yml

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site
...
